spring.application.name=Pizzeria

spring.datasource.url=jdbc:postgresql://localhost:5433/pizzeria
spring.datasource.username=${DB_USERNAME: }
spring.datasource.password=${DB_PASSWORD: }
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.liquibase-schema=public
spring.liquibase.default-schema=public

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=pizza-shop-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*