-- Создание схемы (аналог PostgreSQL)
CREATE SCHEMA IF NOT EXISTS courses1_schema;

-- Таблица courses (используем IDENTITY вместо BIGSERIAL)
CREATE TABLE IF NOT EXISTS courses1_schema.courses (
                                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       name VARCHAR(255) NOT NULL,
                                                       start_date DATE NOT NULL,
                                                       is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Таблица students (IDENTITY + внешний ключ)
CREATE TABLE IF NOT EXISTS courses1_schema.students (
                                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        first_name VARCHAR(255) NOT NULL,
                                                        last_name VARCHAR(255) NOT NULL,
                                                        course_id BIGINT,
                                                        CONSTRAINT fk_student_course
                                                            FOREIGN KEY (course_id)
                                                                REFERENCES courses1_schema.courses(id)
                                                                ON DELETE SET NULL
);

-- Вставка данных (синтаксис совместим с H2 и PostgreSQL)
INSERT INTO courses1_schema.courses (name, start_date, is_active) VALUES
                                                                      ('Java для начинающих', DATE '2024-03-01', true),
                                                                      ('Python: продвинутый уровень', DATE '2024-04-15', true),
                                                                      ('Веб-разработка на JavaScript', DATE '2024-05-10', true),
                                                                      ('Основы SQL и баз данных', DATE '2024-06-01', true),
                                                                      ('Мобильная разработка на Kotlin', DATE '2024-07-20', true),
                                                                      ('Машинное обучение на Python', DATE '2024-08-05', true),
                                                                      ('DevOps: Docker и Kubernetes', DATE '2024-09-12', true);

INSERT INTO courses1_schema.students (first_name, last_name, course_id) VALUES
                                                                            ('Ivan', 'Ivanov', 1),
                                                                            ('Petr', 'Petrov', 1),
                                                                            ('Mariya', 'Sidorova', 2),
                                                                            ('Aleksey', 'Smirnov', 2),
                                                                            ('Elena', 'Kuznetsova', 3),
                                                                            ('Dmitriy', 'Popov', 3),
                                                                            ('Olga', 'Lebedeva', 4),
                                                                            ('Sergey', 'Kozlov', 4),
                                                                            ('Anna', 'Novikova', 5),
                                                                            ('Andrey', 'Morozov', 5),
                                                                            ('Natalya', 'Volkova', 6),
                                                                            ('Artem', 'Solovyev', 6),
                                                                            ('Viktoriya', 'Vasileva', 7),
                                                                            ('Igor', 'Zaytsev', 7),
                                                                            ('Yuliya', 'Pavlova', NULL);