CREATE TABLE IF NOT EXISTS students (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        full_name VARCHAR(255) NOT NULL,
                                        email VARCHAR(100) UNIQUE NOT NULL,
                                        courses TEXT[]
);
COMMENT ON TABLE students IS 'Таблица для учета студентов';

COMMENT ON COLUMN students.id IS 'Уникальный идентификатор студента';
COMMENT ON COLUMN students.full_name IS 'Полное имя студента';
COMMENT ON COLUMN students.email IS 'Адрес электронной почты студента';
COMMENT ON COLUMN students.courses IS 'Список курсов, на которые записан студент';